config/routes.rb
Rails.application.routes.draw do
  get 'presenters/new'
  get 'presenters/edit'
  root 'videos#index'
  resources :videos
  resources :presenters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/description_template.rb
# == Schema Information
#
# Table name: description_templates
#
#  id         :bigint           not null, primary key
#  template   :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class DescriptionTemplate < ApplicationRecord
  has_many :videos
end

app/models/presenter.rb
# == Schema Information
#
# Table name: presenters
#
#  id             :bigint           not null, primary key
#  name           :string           not null
#  twitter_handle :string
#  linked_in      :string
#  role           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Presenter < ApplicationRecord
  has_many :video_presenters
  has_many :videos, through: :video_presenters
end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id                      :bigint           not null, primary key
#  youtube_id              :string           not null
#  title                   :string           not null
#  tags                    :string           default([]), is an Array
#  chapter_markers         :text
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  description_template_id :bigint           not null
#
class Video < ApplicationRecord
  belongs_to :description_template
  has_many :video_presenters
  has_many :presenters, through: :video_presenters
  has_many :video_resources
end

app/models/video_presenter.rb
# == Schema Information
#
# Table name: video_presenters
#
#  id           :bigint           not null, primary key
#  video_id     :bigint           not null
#  presenter_id :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class VideoPresenter < ApplicationRecord
  belongs_to :video
  belongs_to :presenter
end

app/models/video_resource.rb
# == Schema Information
#
# Table name: video_resources
#
#  id         :bigint           not null, primary key
#  url        :string           not null
#  title      :string           not null
#  video_id   :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class VideoResource < ApplicationRecord
  belongs_to :video
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/presenters_controller.rb
class PresentersController < ApplicationController
  def index
    @presenters = Presenter.all
  end
  def new
    @presenter = Presenter.new
  end
  def show
    @presenter = Presenter.find(params[:id])
  end

  def create
    @presenter = Presenter.new(presenter_params)
    if @presenter.save
      redirect_to presenters_path
    else
      flash.now[:error] = @presenter.errors.full_messages
      render :new
    end
  end

  def edit
    @presenter = Presenter.find(params[:id])
    
  end
  def update
    @presenter = Presenter.find(params[:id])
    @presenter.update(
      presenter_params
      )
    redirect_to presenters_path(params[:id])
  end

  private
  def presenter_params
    params.require(:presenter).permit(:name, :twitter_handle, :linked_in, :role)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
  end

  def edit
    @video = Video.find(params[:id])
    @description = DescriptionTemplate.all
  end

  def update
    @video = Video.find(params[:id])
    @video.update(video_params)
    redirect_to videos_path(@video.id)
  end 
  private
  def video_params
    params.require(:video).permit(
      :youtube_id, 
      :title, 
      :tags, 
      :chapter_markers, 
      :description_template, 
      :presenters
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presenters_helper.rb
module PresentersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoAutomation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <header class="bg-gray-800 text-white flex h-10 items-center px-12 py-12">
      <div class="logo flex-auto w-14 ">
        <a class="text-white text-3xl">Video Automation</a>
      </div>
      <nav class="flex-auto w-64">
        <ul class="flex justify-normal gap-4">
          <li class="hover:text-amber-500">
            <a href="/">Home</a>
          </li>
          <li class="hover:text-amber-500">
            <a href="/presenters">Presenters</a>
          </li>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/presenters/_form.html.erb
<div class="presenter__form">
  <%= form_with model: @presenter,  local: true do |f| %>
    <div class="flex gap-8 py-2 px-6">
      <%= f.label :name, :class => 'w-64' %>
      <%= f.text_field :name, class: 'border p-2 text-gray-500 w-80 h-10 outline-transparent' %>
    </div>
    <div class="flex gap-8 py-2 px-6">
      <%= f.label :twitter_handle, :class => 'w-64' %>
      <%= f.text_field :twitter_handle, class: 'border p-2 text-gray-500 w-80 h-10 outline-transparent' %>
    </div>
    <div class="flex gap-8 py-2 px-6">
      <%= f.label :linked_in, :class => 'w-64' %>
      <%= f.text_field :linked_in, class: 'border p-2 text-gray-500 w-80 h-10 outline-transparent' %>
    </div>
    <div class="flex gap-8 py-2 px-6">
      <%= f.label :role, :class => 'w-64' %>
      <%= f.text_field :role, class: 'border p-2 text-gray-500 w-80 h-10 outline-transparent' %>
    </div>
    <div class="flex gap-8 py-2 px-6">
      <%= f.submit 'Save', class: 'w-50 bg-sky-500 text-white py-2 px-6 rounded-md' %>
    </div>
  <% end %>
</div>

app/views/presenters/edit.html.erb
<section class="container__video__show p-8">
  <h1 class="text-4xl underline underline-offset-4 pb-4">Update <%=@presenter.name%> Presenters</h1>
  <%= form_with model: @presenter, local: true, method: :patch, :class => '' do |f| %>
    <div class="flex gap-8 py-2 px-6">
      <%= f.label :name, class: 'w-64' %>
      <%= f.text_field :name, class: 'border p-2 text-gray-500 w-80 h-10 outline-transparent' %>
    </div >
    <div class="flex gap-8 py-2 px-6"> 
      <%= f.label :twitter_handle, class: 'w-64' %>
      <%= f.text_field :twitter_handle, class: 'border p-2 text-gray-500 w-80 h-10 outline-transparent' %>
    </div>
    <div class="flex gap-8 py-2 px-6">
      <%= f.label :linked_in, class: 'w-64' %>
      <%= f.text_field :linked_in, class: 'border p-2 text-gray-500 w-80 h-10 outline-transparent' %>
    </div>
    <div class="flex gap-8 py-2 px-6">
      <%= f.label :role, class: 'w-64' %>
      <%= f.text_field :role, class: 'border p-2 text-gray-500 w-80 h-10 outline-transparent' %>
    </div>
    <div class="flex gap-8 py-2 px-6">
      <%= f.submit 'Update',  class: 'w-50 bg-sky-500 text-white py-2 px-6 rounded-md' %>
    </div>
  <% end %>
</section>

app/views/presenters/index.html.erb
<section class="container__presenter p-8">
  <h1 class="text-4xl mb-4">Presenter's List</h1>
  <span class="material-symbols-outlined bg-sky-500 text-white px-1 py-1 rounded my-4">
    <%= link_to "add", new_presenter_path, class: '' %>
  </span>
  <ul >
    <% @presenters.each do |presenter|%>
    <li class='leading-8 presenter__item'> 
      <%= link_to presenter.name, presenter, :class => 'underline text-sky-500 underline-offset-'%>
    </li>
    <% end %>
  </ul>
</section>

app/views/presenters/new.html.erb
<section class="container__new__presenter p-8">
  <h1 class="text-4xl mb-4">New Presenter</h1>
  <%= render 'form'%>
</section>

app/views/presenters/show.html.erb
<section class="container__video__show p-8">
  <h1 class="text-4xl underline underline-offset-4 pb-4"><%= @presenter.name%></h1>
  <ul class="leading-8">
    <li>
      <span>Twitter Handle: </span>
      <span class="bg-sky-500 rounded p-1 text-white">
        <%= '@' + @presenter.twitter_handle %>
      </span>
    </li>
    <li>
      <span>LinkedIn Handle: </span>
      <span class="bg-sky-500 rounded p-1 text-white">
        <%= @presenter.linked_in%>
      </span>
    </li>
    <li>
      <span>Role: </span>
      <span class="bg-sky-500 rounded p-1 text-white">
        <%= @presenter.role%>
      </span>
    </li>
  </ul>

  <%= link_to "Edit Presenter", edit_presenter_path(@presenter), class: 'underline text-sky-500 underline-offset-4 text-2xl mt-4' %>
</section>

app/views/videos/edit.html.erb
<section class="container__edit_video">
  <h1 class="w-100 bg-gray-400 text-center py-4 text-3xl text-white"> Editing <%= @video.title%></h1>
  <%= form_for @video, {:class => 'w-80 m-auto bg-amber-500'} do |f| %>
    <div class="flex gap-8 py-2 px-6">
      <%= f.label :description_template, 'Description Template', :class => 'w-64' %>
      <select class="border p-2 text-gray-500 w-80 h-10  outline-transparent">
        <%@description.each do |template|%>
          <option value="<%= template.id%>">
          <%= template.name%>|<%= template.id%>
          </option>
        <%end%>
      </select>
    </div>
    <div class="flex gap-8 py-2 px-6">
      <%= f.label :title, 'Title', :class => 'w-64' %>
      <%= f.text_field :title, :class => 'border p-2 text-gray-500 w-80 h-10 outline-transparent' %>
    </div>
    <div class="flex gap-8 py-2 px-6">
      <%= f.label :tags, 'Tags', :class => 'w-64' %>
      <%= f.text_area :tags, :value => @video.tags.join(','), :cols => 50, :rows => 5, :class => 'border p-2 text-gray-500 w-80 h-18 outline-transparent' %>
    </div>
    <div class="flex gap-8 py-2 px-6">
      <%= f.label :chapter_markers, 'Chapter Markers', :class => 'w-64' %>
      <%= f.text_area :chapter_markers, :class => 'border p-2 text-gray-500 w-80 h-18 outline-transparent' %>
    </div>
    <div class="flex gap-8 py-2 px-6">
      <%= f.submit 'Edit Video', class: 'w-100 bg-sky-500 text-white py-2 px-6 rounded-md' %>
    </div>
  <% end %>
</section>

app/views/videos/index.html.erb
<section class="container__videos p-8">
  <h1 class="text-4xl ">Videos</h1>
  <ul class="grid p-2 grid-cols-4 gap-2">
    <% @videos.each do |video|%>
      <li class="flex gap-2 border relative rounded-l-lg overflow-hidden">
        <iframe 
        width="120" 
        height="80" 
        src="https://www.youtube.com/embed/<%=video.youtube_id%>" 
        title="YouTube video player" 
        frameborder="0" 
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        <%= link_to video.title, video, class: 'pt-2 text-1xl underline decoration-red-500 underline-offset-4 decoration-wavy text-gray-800 hover:text-blue-600' %>
        <ul class='absolute bottom-2 left-32 text-xs flex gap-2'>
          <% video.tags.map do |tag|%>
            <li class="bg-gray-300 rounded-full px-2 py-1"><%= tag%></li>
          <% end%>
        </ul>
      </li>
      
    <% end %>
  </ul>
</section>

app/views/videos/show.html.erb
<section class="container__video p-8">
  <h1 class="text-4xl underline underline-offset-4"> <%= @video.title%></h1>
  <ul class="flex gap-6 py-6 px-12"> 
    <li>
      <iframe 
        width="560" 
        height="315" 
        src="https://www.youtube.com/embed/<%=@video.youtube_id%>" 
        title="YouTube video player" 
        frameborder="0" 
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </li>
    <div class="leading-loose">
    <li>
      Tags: 
      <ul class="flex gap-2">
        <% @video.tags.map do |tag|%>
          <li class="bg-sky-500 text-white rounded-md px-2 py-1/4"><%= tag%></li>
        <% end%>
      </ul>
    </li>
    <li>
      Chapter Markers: 
      <%= @video.chapter_markers%>
    </li>
    <li>
      Template: <%= @video.description_template.template%>
    </li>
      <%= link_to 'Edit',  edit_video_path(@video), :class => "underline text-sky-500 underline-offset-4"%>
    </div>
  </ul>
</section>